// /*
//  * This file was generated by the Gradle 'init' task.
//  *
//  * This generated file contains a sample Kotlin application project to get you started.
//  * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
//  */

// plugins {
//     // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
//     alias(libs.plugins.kotlin.jvm)

//     // Apply the application plugin to add support for building a CLI application in Java.
//     application
// }

// repositories {
//     // Use Maven Central for resolving dependencies.
//     mavenCentral()
// }

// dependencies {
//     // Use JUnit Jupiter for testing.
//     testImplementation(libs.junit.jupiter)

//     testRuntimeOnly("org.junit.platform:junit-platform-launcher")

//     // This dependency is used by the application.
//     implementation(libs.guava)
// }

// // Apply a specific Java toolchain to ease working on different environments.
// java {
//     toolchain {
//         languageVersion = JavaLanguageVersion.of(17)
//     }
// }

// application {
//     // Define the main class for the application.
//     mainClass = "org.example.AppKt"
// }

// tasks.named<Test>("test") {
//     // Use JUnit Platform for unit tests.
//     useJUnitPlatform()
// }
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.example.clippyshare"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.clippyshare"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.11.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
}
